   
name: Deploy av API code to a VM
author: Vladyslav Martyshev
description: Simple multi-step composite action to be used as a single step. Deploys code to vms via SSH.

inputs:
  vm:
    description: 'The name of the GCP compute engine vm'
    required: true
    default: 'csci-clamav-vm'
  zone:
    description: 'The name of the GCP compute engine vm zone'
    required: true
    default: 'europe-west1-b'
  user:
    description: 'The name of the GCP compute engine non root user'
    required: true
    default: 'avapi'
  directory:
    description: 'The name of the repo dir to copy files from'
    required: true
    default: 'clamav'

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
  
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name Output
      run: echo "VM_anme=test >> GITHUB_OUTPUT"
      shell: bash
    #run: echo "VM_anme=${{ inputs.vm }} >> GITHUB_OUTPUT"
    # - name: Stop avapi service        
    #   run: |
    #           gcloud compute ssh ubuntu@csci-clamav-vm --zone=europe-west1-b --command 'sudo systemctl stop avapi'
    
    # - name: Copy files
    #   #if: success() || failure()       
    #   run:        
    #           gcloud compute scp --zone=europe-west1-b --recurse  clamav/* avapi@csci-clamav-vm:/home/avapi/
              
    # - name:  Install python packages     
    #   run:         
    #           gcloud compute ssh avapi@csci-clamav-vm --zone=europe-west1-b --command 'pip install --user -r /home/avapi/requirements.txt'
            
    # - name: Start avapi service        
    #   run:            
    #           gcloud compute ssh ubuntu@csci-clamav-vm --zone=europe-west1-b --command 'sudo systemctl start avapi'
