name: 'PR title and body check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize


jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:

      - id: check
        run: |
              TITLE='^.{13,72}$'
              BODY='AB#[0-9]{6,10}'

              if [[ ! "${{ github.event.pull_request.title }}" =~ $BODY && "${{ github.event.pull_request.title }}" =~ $TITLE && "${{ github.event.pull_request.body }}" =~ $BODY ]]; then
                echo "it's a match!"
              else
                echo "NO!" >> "$GIRHUB_OUTPUT"
                exit 1
              fi
  pr_comment:
    name: PR comment with reactions
    uses: thollander/actions-comment-pull-request@v2
    with:
      message: |
        Hello world ! :wave:
      reactions: eyes, rocket

