name: Detect changes

on:
  pull_request:
    branches:
     - main

jobs:
    changed_files:
      runs-on: ubuntu-latest
      name: Test changed-files
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

        # Example 1
        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v40.2.0
          with:
            dir_names: true
            dir_names_exclude_current_dir: true
            dir_names_max_depth: '1'
            json: true
            quotepath: false
            escape_json: false
            files_ignore: .github/**
        - run: |
              echo  ${{ steps.changed-files.outputs.all_changed_and_modified_files }}


        - uses: ./.github/workflows/deploy.yaml
          with:
            env_value: 'dev'
            matrix_value: ${{steps.changed-files.outputs}}




