name: Matrix variable play

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  dir_listing:
    runs-on: 'ubuntu-latest'
    outputs:
      dirlist: ${{ steps.dirs-output.outputs.dirs }}
    steps:
    - id: dirs-output
      uses: 'actions/checkout@v4'
    - run: |
            #arr-json=$(ls  -d */ | jq -R | jq -s -c)
            #echo $arr-json
            #echo  "dirs=$(ls  -d */ | jq -R | jq -s -c)" >> "$GITHUB_OUTPUT"
            echo  "dirs='Hello!'" >> "$GITHUB_OUTPUT"

  
  test_matrix:
    runs-on: 'ubuntu-latest'
    needs: dir_listing
    env:
      DIRS: ${{needs.dir_listing.outputs.dirlist}}  
    #environment: prod
    strategy:
      matrix:
        list: ['stepone', 'steptwo', 'stepthree']
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: output
      run: |
           echo ${{matrix.list}} 
           echo ${{needs.dir_listing.outputs.dirlist}}
