name: Matrix variable play

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  dir_listing:
    runs-on: 'ubuntu-latest'
    outputs:
      output1: ${{ steps.dirs-output.outputs.dirs }}
    steps:
    - id: checkout
      uses: 'actions/checkout@v4' 

    - id: dirs-output
      run: echo  "dirs=$(ls -d */ | sed 's/\/$//' | jq -R | jq -s -c)" >> "$GITHUB_OUTPUT"
            
    - id: print
      name: print
      run: echo ${{ steps.dirs-output.outputs.dirs }} 

  test_matrix:
    runs-on: 'ubuntu-latest'
    needs: dir_listing
     
    #environment: prod
    strategy:
      matrix:
        list: ${{ fromJSON(needs.dir_listing.outputs.output1)}}
    
    steps:
    - env:
        OUTPUT1: ${{ needs.dir_listing.outputs.output1 }} 
      id: output
      name: Output 
      #if: github.event_name != 'push'
      run: |
           #echo ${{ matrix.list }} 
           echo $OUTPUT1
     
    - name: setup-gh
      uses: wusatosi/setup-gh@v1.1
       
    - run: echo $(gh release list --exclude-drafts --exclude-pre-releases -L 2|grep Latest|cut  -f3)
       
