name: Matrix variable play

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  dir_listing:
    runs-on: 'ubuntu-latest'
    outputs:
      dirlist: ${{ steps.dirs-output.outputs.dirs }}
    steps:
    - id: dirs-output
      uses: 'actions/checkout@v4'
    - run: |
          echo  "dirs=$(ls -d */ | cut -f1 -d'/')" >> $GITHUB_OUTPUT
  
  test_matrix:
    runs-on: 'ubuntu-latest'
    needs: dir_listing
    #environment: prod
    strategy:
      matrix:
        list: ['stepone', 'steptwo', 'stepthree']
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: output
      run: |
           echo ${{matrix.list}} 
           echo ${{needs.dir_listing.outputs.dirlist}}
