name: Matrix variable play

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  dir_listing:
    runs-on: 'ubuntu-latest'
    outputs:
      output1: ${{ steps.dirs-output.outputs.dirs }}
    steps:
    - id: dirs-output
      #uses: 'actions/checkout@v4'
      run: echo  "dirs=1" >> "$GITHUB_OUTPUT"
            #arr-json=$(ls  -d */ | jq -R | jq -s -c)
            #echo $arr-json
            #echo  "dirs=$(ls  -d */ | jq -R | jq -s -c)" >> "$GITHUB_OUTPUT"
            #echo  "dirs=1" >> "$GITHUB_OUTPUT"
    - id: print
      name: print
      run: echo ${{ steps.dirs-output.outputs.dirs }} 

  test_matrix:
    runs-on: 'ubuntu-latest'
    needs: dir_listing
     
    #environment: prod
    #strategy:
    #  matrix:
    #    list: ['stepone', 'steptwo', 'stepthree']
    
    steps:
    - env:
        OUTPUT1: ${{ needs.dir_listing.outputs.output1 }} 
      id: output
      name: Output 
      run: |
           #echo ${{ matrix.list }} 
           echo $OUTPUT1
