name: Parse cf config
on: 
  workflow_dispatch

jobs:
  Parse_config:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: 'actions/checkout@v4'
    - id: get_cf_config
      run: |
        # Function to set configuration with default
        set_config() {
          local var_name=$1
          local value=$2
          local default_value=$3
    
          if [ -z "$value" ]; then
            echo "$var_name=$default_value" >> $GITHUB_OUTPUT
          else
            echo "$var_name=$value" >> $GITHUB_OUTPUT
          fi
        }
    
        # Default values
        declare -A defaults=(
          [memory]="256MB"
          [timeout]=60
          [gen]=1
          [ingress]="internal-only"
          [cpu]="10"
        )
    
        config_file="config.conf"
        if [ -f "$config_file" ]; then
          source "$config_file"
          for key in "${!defaults[@]}"; do
            set_config "$key" "${!key}" "${defaults[$key]}"
          done
        else
          for key in "${!defaults[@]}"; do
            echo "$key=${defaults[$key]}" >> $GITHUB_OUTPUT
          done
        fi


    - id: output
      run: |
            echo ${{ steps.get_cf_config.outputs.memory}} >> $GITHUB_STEP_SUMMARY
            echo ${{ steps.get_cf_config.outputs.timeout}} >> $GITHUB_STEP_SUMMARY
            echo ${{ steps.get_cf_config.outputs.gen}} >> $GITHUB_STEP_SUMMARY
            echo ${{ steps.get_cf_config.outputs.ingress}} >> $GITHUB_STEP_SUMMARY
            echo ${{ steps.get_cf_config.outputs.cpu}} >> $GITHUB_STEP_SUMMARY

         