name: Steps output
on:
  workflow_dispatch:

jobs:
  stepjob:
    runs-on: ubuntu-latest
    #continue-on-error: true

    steps:
      - id: step1
        run: |
            echo Success!
            exit 1
            if ( always )
      - id: step2 
        if: failure()
        run: |
            echo Failed!
            exit 0
    
  outputjob:
    runs-on: ubuntu-latest
    needs: stepjob
    steps:
      - run: echo ${{ needs.stepjob.result }}

