name: Steps output
on:
  workflow_dispatch:

jobs:
  stepjob:
    runs-on: ubuntu-latest

    steps:
      - id: step1
        run: |
            echo Success!
            exit 0
            if ( always )
      - id: step2 
        run: |
            echo Failed!
            exit 1
    
  outputjob:
    runs-on: ubuntu-latest
    needs: stepjob
    steps:
      - run: echo ${{ needs.stepjob.result }}

