name: "Var play"

on:
    workflow_dispatch:
jobs:
  vars:
    runs-on: [ubuntu-latest]
    #permissions:
    steps:
    # - id: 'nameextract'
    #   run: |
    #           NAME="$( echo ${{ vars.cloud_functions }} | sed -r 's/-+/_/g' )"_mem
    #           echo $NAME
    #           echo "$NAME"_mem
    #           NAME2=vars."$NAME"
    #           echo ${{ '$(NAME2)' }}
    #           if [ ${{ '$NAME2' }} == ${{ null }} ]; then
    #             echo "TRUE"
    #           else
    #             echo "FALSE"
    #           fi

    - id: conf_var_output
      env:
        cf_name: 'MYVAR'
        
        
      run: |     
            echo "var_name="vars."$cf_name"_MEM"" >> $GITHUB_ENV
            name: $var_name
            echo $name
    - id: step2
      run: echo ${{ env.var_name }}
      
           
           
   