name: "Var play"

on:
    push:
    workflow_dispatch:
env:
  cf_name: MYVAR
jobs:
  vars:
    runs-on: [ubuntu-latest]
    #permissions:
    steps:
    # - id: 'nameextract'
    #   run: |
    #           NAME="$( echo ${{ vars.cloud_functions }} | sed -r 's/-+/_/g' )"_mem
    #           echo $NAME
    #           echo "$NAME"_mem
    #           NAME2=vars."$NAME"
    #           echo ${{ '$(NAME2)' }}
    #           if [ ${{ '$NAME2' }} == ${{ null }} ]; then
    #             echo "TRUE"
    #           else
    #             echo "FALSE"
    #           fi

    - id: conf_var_output
      run: |
             name="vars."$cf_name"_MEM"
             echo $name
             echo ${{ vars.MYVAR_MEM }}
     
  
      
           
           
   