name: "Var play"

on:
    workflow_dispatch:
jobs:
  vars:
    runs-on: [ubuntu-latest]
    #permissions:
    steps:
    - id: 'nameextract'
      run: |
              NAME="$( echo ${{ vars.cloud_functions }} | sed -r 's/-+/_/g' )"_mem
              echo $NAME
              echo "$NAME"_mem
              NAME2=vars."$NAME"
              echo ${{ '$(NAME2)' }}
              if [ ${{ '$NAME2' }} == ${{ null }} ]; then
                echo "TRUE"
              else
                echo "FALSE"
              fi

    - id: conf_var_output
      run: |
            echo ${{ vars.myvar }}_MEM  
            echo vars."${{ vars.MYVAR }}"_MEM 
            echo ${{ vars.MYVAR }}"_MEM" 
            echo "${{ vars.MYVAR }}_MEM" 
            export var_name=${{vars.myvar}}
            MEM=[[ ${{ $var_name }}  != '' ]] && ${{ $var_name }} || 256
            echo $MEM


   