name: "Var play"

on:
    workflow_dispatch:
jobs:
  vars:
    runs-on: [ubuntu-latest]
    #permissions:
    steps:
    - id: 'nameextract'
      run: |
              NAME="$( echo ${{ vars.cloud_functions }} | sed -r 's/-+/_/g' )"_mem
              echo $NAME
              echo "$NAME"_mem
              if [ ${{ 'vars.$NAME' }} == ${{ null}} ]; then
                echo "TRUE"
              else
                echo "FALSE"
              fi


