name: "Var play"

on:
    workflow_dispatch:
jobs:
  vars:
    runs-on: [ubuntu-latest]
    #permissions:
    steps:
    - id: 'nameextract'
      run: |
              NAME="$( echo ${{ vars.cloud_functions }} | sed -r 's/-+/_/g' )"_mem
              echo $NAME
              echo "$NAME"_mem
              NAME2=vars."$NAME"
              echo ${{ 'vars.$(NAME)' }}
              if [ ${{ '$NAME2' }} == ${{ null }} ]; then
                echo "TRUE"
              else
                echo "FALSE"
              fi


